sudo: false

language: java

cache:
  directories:
  - $HOME/.m2

after_success:
  - mvn clean test jacoco:report coveralls:report

addons:
  coverity_scan:
    project:
      name: "resios/cron"
      description: "Build submitted via Travis CI"
    notification_email: andrei.resios@gmail.com
    build_command_prepend: "mvn clean"
    build_command:   "mvn -DskipTests=true compile"
    branch_pattern: master

